"""fix enrollment primary key

Revision ID: 8ecaf613a4ce
Revises: f1a20e989839
Create Date: 2026-08-22 22:27:58.013605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ecaf613a4ce'
down_revision: Union[str, Sequence[str], None] = 'f1a20e989839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.execute("""
        ALTER TABLE enrollments
        ALTER COLUMN id
        ADD GENERATED BY DEFAULT AS IDENTITY
    """)


def downgrade():
    op.execute("""
        ALTER TABLE enrollments
        ALTER COLUMN id
        DROP IDENTITY
    """)
